import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { Navbar, Footer } from "@/components";
import CTASection from "@/components/sections/CTASection";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} content-grid font-satoshi`}>
        <NextTopLoader color="#000" easing="easeInOut" />
        <Navbar />
        <main className="full-width content-grid mt-[3.5rem] md:mt-[4rem] lg:mt-[6rem]">
          {children}
        </main>
        <CTASection />
        <Footer />
      </body>
    </html>
  );
}
